import type { AdministrationDetail, FluidAdministrationDetail, NurseDrugOrder } from "./types";

export const medicationTimeSlots = Array.from({ length: 24 }, (_, hour) => `${String(hour).padStart(2, "0")}:00`);

export const nurseDrugOrders: NurseDrugOrder[] = [
  {
    id: "nd-001",
    category: "Scheduled",
    name: "Paracetamol",
    form: "Tablet",
    dosage: "650 mg",
    frequency: "TDS",
    days: "3",
    route: "Oral",
    instructions: "After food. Check temperature before administration.",
    orderedQty: 9,
    dispensedQty: 9,
    receivedQty: 9,
    administeredQty: 4,
    taperedDose: "No taper",
    lastAdministeredAt: "06:05",
    lastAdministeredBy: "Nisha Thomas",
    cells: [
      { time: "06:00", label: "650 mg", status: "administered" },
      { time: "07:00", label: "Overdue 650 mg", status: "overdue" },
      { time: "09:00", label: "650 mg due", status: "due" },
      { time: "12:00", label: "650 mg", status: "administered" },
      { time: "18:00", label: "650 mg", status: "administered" },
    ],
  },
  {
    id: "nd-002",
    category: "Scheduled",
    name: "Pantoprazole",
    form: "Injection",
    dosage: "10 mg",
    frequency: "BD",
    days: "2",
    route: "IV",
    instructions: "Dilute and give slow IV.",
    orderedQty: 4,
    dispensedQty: 2,
    receivedQty: 1,
    administeredQty: 1,
    lastAdministeredAt: "12:05",
    lastAdministeredBy: "Maya Iyer",
    cells: [
      { time: "06:00", label: "10 mg due", status: "due" },
      { time: "12:00", label: "10 mg", status: "administered" },
    ],
  },
  {
    id: "nd-003",
    category: "SOS",
    name: "Ondansetron",
    form: "Injection",
    dosage: "4 mg",
    frequency: "SOS",
    days: "1",
    route: "IV",
    instructions: "For nausea/vomiting. Record indication before giving.",
    orderedQty: 3,
    dispensedQty: 3,
    receivedQty: 3,
    administeredQty: 1,
    lastAdministeredAt: "03:20",
    lastAdministeredBy: "Nisha Thomas",
    cells: [
      { time: "03:00", label: "4 mg", status: "administered" },
      { time: "05:00", label: "SOS dose", status: "due" },
      { time: "16:00", label: "SOS dose", status: "due" },
    ],
  },
  {
    id: "nd-004",
    category: "Intermittent",
    name: "Ceftriaxone",
    form: "Injection",
    dosage: "1 g",
    frequency: "BD",
    days: "5",
    route: "IV",
    instructions: "Flush line before and after dose.",
    orderedQty: 10,
    dispensedQty: 6,
    receivedQty: 4,
    administeredQty: 2,
    bolusDose: "1 g",
    bagVolume: 100,
    administeredVolume: 40,
    bagCount: 1,
    lastAdministeredAt: "08:15",
    lastAdministeredBy: "Maya Iyer",
    cells: [
      { time: "08:00", label: "IV antibiotic 1 g", status: "due" },
      { time: "09:00", label: "IV antibiotic given", status: "administered" },
      { time: "14:00", label: "IV antibiotic 1 g", status: "due" },
    ],
  },
  {
    id: "nd-005",
    category: "Continuous",
    name: "Normal Saline",
    form: "IV Fluid",
    dosage: "20 ml/hr",
    frequency: "Continuous",
    days: "1",
    route: "IV",
    instructions: "Monitor intake/output and bag balance.",
    orderedQty: 3,
    dispensedQty: 2,
    receivedQty: 2,
    administeredQty: 1,
    bolusDose: "20 ml",
    bagVolume: 500,
    administeredVolume: 180,
    bagCount: 1,
    lastAdministeredAt: "10:00",
    lastAdministeredBy: "Nisha Thomas",
    cells: [
      { time: "08:00", label: "IV bolus 20 ml", status: "bolus" },
      { time: "09:00", label: "IV bolus 20 ml", status: "bolus" },
      { time: "10:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "11:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "12:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "13:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "14:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "15:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "16:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "17:00", label: "Infusion 20 ml/hr", status: "infusion" },
      { time: "18:00", label: "Infusion 20 ml/hr", status: "infusion" },
    ],
  },
  {
    id: "nd-006",
    category: "Discontinued",
    name: "Ibuprofen",
    form: "Tablet",
    dosage: "400 mg",
    frequency: "BD",
    days: "0",
    route: "Oral",
    instructions: "Stopped due gastritis.",
    orderedQty: 10,
    dispensedQty: 10,
    receivedQty: 10,
    administeredQty: 2,
    discontinuedReason: "Gastritis",
    lastAdministeredAt: "Yesterday 20:00",
    lastAdministeredBy: "Maya Iyer",
    cells: [
      { time: "08:00", label: "Stopped by doctor", status: "empty" },
    ],
  },
  {
    id: "nd-007",
    category: "Unscheduled",
    name: "Calamine",
    form: "Cream",
    dosage: "Thin layer",
    frequency: "",
    days: "",
    route: "Topical",
    instructions: "Apply if itching.",
    orderedQty: 1,
    dispensedQty: 0,
    receivedQty: 0,
    administeredQty: 0,
    cells: [
      { time: "11:00", label: "Thin layer", status: "due" },
    ],
  },
];

export const defaultAdministrationDetail: AdministrationDetail = {
  orderId: "nd-001",
  orderName: "Paracetamol",
  category: "Scheduled",
  administrationDate: "2026-05-26",
  dosage: "650 mg",
  time: "07:00",
  lastAdministeredAt: "06:05",
  lastAdministeredBy: "Nisha Thomas",
  action: "Late administered",
  reason: "Scheduled dose overdue",
  counterChecked: false,
  counterCheckedBy: "",
  counterCheckedAt: "",
};

export const defaultFluidDetail: FluidAdministrationDetail = {
  orderId: "nd-005",
  orderName: "Normal Saline",
  category: "Continuous",
  administrationDate: "2026-05-26",
  rate: "20 ml/hr",
  time: "10:00",
  lastAdministeredAt: "10:00",
  lastAdministeredBy: "Nisha Thomas",
  counterCheckedBy: "",
  counterCheckedAt: "",
  counterChecked: false,
  bagVolume: "500",
  volumeAdministered: "180",
  volumeRemaining: "320",
  newBag: false,
  bagCount: "1",
  bolusDose: "20 ml",
  stopAdministrationAt: "",
  reason: "",
};
