import type { AdministrationDetail, FluidAdministrationDetail, NurseDrugOrder } from "./types";

export const medicationTimeSlots = Array.from(
  { length: 24 },
  (_, hour) => `${String(hour).padStart(2, "0")}:00`
);

export const nurseDrugCategories: NurseDrugOrder["category"][] = [
  "Scheduled",
  "SOS",
  "STAT",
  "Bolus",
  "Diluent",
  "Intermittent",
  "Continuous",
  "Discontinued",
  "Unscheduled",
];

export const nurseDrugOrders: NurseDrugOrder[] = [
  {
    id: "nd-001",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    mrn: "MRN-1001",
    ward: "ICU",
    bed: "B-12",
    orderNumber: "ORD-001",
    orderType: "Drug Order",
    orderedBy: "Dr. Kamal",
    prescriber: "Dr. Kamal",
    category: "Scheduled",
    name: "Paracetamol",
    drugName: "Paracetamol",
    genericName: "Paracetamol",
    brandName: "Dolo 650",
    form: "Tablet",
    strength: "650 mg",
    dosage: "650 mg",
    dose: "650",
    doseUnit: "mg",
    frequency: "TDS",
    days: "3",
    route: "Oral",
    instructions: "After food. Check temperature before administration.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Due",
    status: "Due",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-07-02",
    scheduledTime: "09:00",
    nextDueTime: "09:00",
    orderedQty: 9,
    dispensedQty: 9,
    receivedQty: 9,
    administeredQty: 4,
    remainingQty: 5,
    orderedDrugName: "Paracetamol",
    orderedDose: "650",
    orderedDoseUnit: "mg",
    orderedRoute: "Oral",
    orderedForm: "Tablet",
    dispensedDrugName: "Paracetamol",
    dispensedDose: "650",
    dispensedDoseUnit: "mg",
    dispensedRoute: "Oral",
    dispensedForm: "Tablet",
    receivedDrugName: "Paracetamol",
    receivedDose: "650",
    receivedDoseUnit: "mg",
    receivedRoute: "Oral",
    receivedForm: "Tablet",
    batchNo: "PCM-650-01",
    expiryDate: "2027-12-31",
    reconciliationStatus: "Matched",
    rightPatientStatus: "Verified",
    rightDrugStatus: "Verified",
    rightDoseStatus: "Verified",
    rightRouteStatus: "Verified",
    rightTimeStatus: "Verified",
    lastAdministeredAt: "06:05",
    lastAdministeredBy: "Nisha Thomas",
    cells: [{ date: "2026-06-30", time: "09:00", label: "650 mg due", status: "due" }],
  },

  {
    id: "nd-002",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    mrn: "MRN-1001",
    ward: "ICU",
    bed: "B-12",
    orderNumber: "ORD-002",
    orderedBy: "Dr. Kamal",
    prescriber: "Dr. Kamal",
    category: "Scheduled",
    name: "Pantoprazole",
    drugName: "Pantoprazole",
    genericName: "Pantoprazole",
    form: "Injection",
    strength: "40 mg",
    dosage: "40 mg",
    dose: "40",
    doseUnit: "mg",
    frequency: "BD",
    days: "2",
    route: "IV",
    instructions: "Dilute and give slow IV.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Overdue",
    status: "Overdue",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-07-01",
    scheduledTime: "07:00",
    nextDueTime: "07:00",
    orderedQty: 4,
    dispensedQty: 4,
    receivedQty: 4,
    administeredQty: 1,
    remainingQty: 3,
    orderedDrugName: "Pantoprazole",
    orderedDose: "40",
    orderedDoseUnit: "mg",
    orderedRoute: "IV",
    orderedForm: "Injection",
    dispensedDrugName: "Pantoprazole",
    dispensedDose: "40",
    dispensedDoseUnit: "mg",
    dispensedRoute: "IV",
    dispensedForm: "Injection",
    receivedDrugName: "Pantoprazole",
    receivedDose: "40",
    receivedDoseUnit: "mg",
    receivedRoute: "IV",
    receivedForm: "Injection",
    batchNo: "PAN-IV-01",
    expiryDate: "2027-08-31",
    reconciliationStatus: "Matched",
    rightPatientStatus: "Verified",
    rightDrugStatus: "Verified",
    rightDoseStatus: "Verified",
    rightRouteStatus: "Verified",
    rightTimeStatus: "Warning",
    rightTimeReason: "Medication is overdue.",
    lastAdministeredAt: "06:05",
    lastAdministeredBy: "Maya Iyer",
    cells: [{ date: "2026-06-30", time: "07:00", label: "40 mg overdue", status: "overdue" }],
  },

  {
    id: "nd-003",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    category: "SOS",
    name: "Ondansetron",
    drugName: "Ondansetron",
    genericName: "Ondansetron",
    form: "Injection",
    strength: "4 mg",
    dosage: "4 mg",
    dose: "4",
    doseUnit: "mg",
    frequency: "SOS",
    days: "1",
    route: "IV",
    instructions: "For nausea/vomiting. Record indication before giving.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Administered",
    status: "Administered",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-06-30",
    scheduledTime: "03:00",
    nextDueTime: "16:00",
    orderedQty: 3,
    dispensedQty: 3,
    receivedQty: 3,
    administeredQty: 1,
    remainingQty: 2,
    reconciliationStatus: "Matched",
    rightPatientStatus: "Verified",
    rightDrugStatus: "Verified",
    rightDoseStatus: "Verified",
    rightRouteStatus: "Verified",
    rightTimeStatus: "Verified",
    lastAdministeredAt: "03:20",
    lastAdministeredBy: "Nisha Thomas",
    cells: [
      { date: "2026-06-30", time: "03:00", label: "4 mg", status: "administered" },
      { date: "2026-06-30", time: "16:00", label: "SOS dose", status: "due" },
    ],
  },

  {
  id: "nd-004",
  category: "STAT",
  name: "Hydrocortisone",
  drugName: "Hydrocortisone",
  genericName: "Hydrocortisone",
  form: "Injection",
  strength: "100 mg",
  dosage: "100 mg",
  dose: "100",
  doseUnit: "mg",
  frequency: "STAT",
  days: "1",
  route: "IV",
  instructions: "Give immediately after verifying vitals.",
  priority: "Immediate",

  orderStatus: "Received",
  administrationStatus: "Due",
  status: "Due",

  orderedQty: 1,
  dispensedQty: 1,
  receivedQty: 1,
  administeredQty: 0,
  remainingQty: 1,

  // Medicine Reconciliation Mismatch
  orderedDrugName: "Hydrocortisone",
  orderedDose: "100",
  orderedDoseUnit: "mg",
  orderedRoute: "IV",
  orderedForm: "Injection",

  dispensedDrugName: "Hydrocortisone Sodium Succinate",
  dispensedDose: "100",
  dispensedDoseUnit: "mg",
  dispensedRoute: "IV",
  dispensedForm: "Injection",

  receivedDrugName: "Hydrocortisone 200 mg IM Injection",
  receivedDose: "200",
  receivedDoseUnit: "mg",
  receivedRoute: "IM",
  receivedForm: "Injection",

  batchNo: "HYD-STAT-01",
  expiryDate: "2027-09-30",

  reconciliationStatus: "Mismatch",
  reconciliationRemarks: "Ordered Hydrocortisone 100 mg IV, but received Hydrocortisone 200 mg IM Injection.",

  rightPatientStatus: "Verified",
  rightDrugStatus: "Failed",
  rightDrugReason: "Received drug label does not match ordered drug.",
  rightDoseStatus: "Failed",
  rightDoseReason: "Ordered dose is 100 mg, received dose is 200 mg.",
  rightRouteStatus: "Failed",
  rightRouteReason: "Ordered route is IV, received route is IM.",
  rightTimeStatus: "Verified",

  cells: [
    {
      date: "2026-06-30",
      time: "10:00",
      label: "100 mg STAT",
      status: "due",
    },
  ],
},

  {
    id: "nd-005",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    category: "Bolus",
    name: "Normal Saline Flush",
    drugName: "Normal Saline Flush",
    genericName: "Sodium Chloride",
    form: "IV Fluid",
    strength: "20 ml",
    dosage: "20 ml",
    dose: "20",
    doseUnit: "ml",
    frequency: "Once",
    days: "1",
    route: "IV",
    instructions: "Give as IV bolus before infusion.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Due",
    status: "Due",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-06-30",
    scheduledTime: "08:00",
    nextDueTime: "08:00",
    orderedQty: 1,
    dispensedQty: 1,
    receivedQty: 1,
    administeredQty: 0,
    remainingQty: 1,
    bolusDose: "20 ml",
    bolusRoute: "IV push",
    reconciliationStatus: "Matched",
    rightPatientStatus: "Verified",
    rightDrugStatus: "Verified",
    rightDoseStatus: "Verified",
    rightRouteStatus: "Verified",
    rightTimeStatus: "Verified",
    cells: [{ date: "2026-06-30", time: "08:00", label: "20 ml bolus", status: "bolus" }],
  },

  {
    id: "nd-006",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    category: "Continuous",
    name: "Normal Saline",
    drugName: "Normal Saline",
    genericName: "Sodium Chloride",
    form: "IV Fluid",
    strength: "20 ml/hr",
    dosage: "20 ml/hr",
    dose: "20",
    doseUnit: "ml/hr",
    frequency: "Continuous",
    days: "1",
    route: "IV",
    instructions: "Monitor intake/output and bag balance.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Running",
    status: "Running",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-06-30",
    scheduledTime: "10:00",
    nextDueTime: "Running",
    orderedQty: 3,
    dispensedQty: 2,
    receivedQty: 2,
    administeredQty: 1,
    remainingQty: 1,
    diluent: "Normal Saline",
    infusionRate: "20 ml/hr",
    bagVolume: 500,
    administeredVolume: 180,
    bagCount: 1,
    reconciliationStatus: "Matched",
    cells: [
      { date: "2026-06-30", time: "10:00", label: "20 ml/hr running", status: "infusion" },
      { date: "2026-06-30", time: "11:00", label: "20 ml/hr running", status: "running" },
      { date: "2026-06-30", time: "12:00", label: "20 ml/hr running", status: "running" },
    ],
  },

  {
    id: "nd-007",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    category: "Scheduled",
    name: "Amlodipine",
    drugName: "Amlodipine",
    genericName: "Amlodipine",
    form: "Tablet",
    strength: "5 mg",
    dosage: "5 mg",
    dose: "5",
    doseUnit: "mg",
    frequency: "OD",
    days: "3",
    route: "Oral",
    instructions: "Hold if BP is low.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Held",
    status: "Held",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-07-02",
    scheduledTime: "09:00",
    nextDueTime: "Review",
    orderedQty: 3,
    dispensedQty: 3,
    receivedQty: 3,
    administeredQty: 0,
    remainingQty: 3,
    holdReason: "Low BP",
    cells: [{ date: "2026-06-30", time: "09:00", label: "5 mg held", status: "held" }],
  },

  {
    id: "nd-008",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    category: "Scheduled",
    name: "Metformin",
    drugName: "Metformin",
    genericName: "Metformin",
    form: "Tablet",
    strength: "500 mg",
    dosage: "500 mg",
    dose: "500",
    doseUnit: "mg",
    frequency: "BD",
    days: "3",
    route: "Oral",
    instructions: "Give after food.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Missed",
    status: "Missed",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-07-02",
    scheduledTime: "12:00",
    nextDueTime: "Review",
    orderedQty: 6,
    dispensedQty: 6,
    receivedQty: 6,
    administeredQty: 1,
    remainingQty: 5,
    missedReason: "Patient was in procedure",
    cells: [{ date: "2026-06-30", time: "12:00", label: "500 mg missed", status: "missed" }],
  },

  {
    id: "nd-009",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    category: "Scheduled",
    name: "Iron Tablet",
    drugName: "Iron Tablet",
    genericName: "Ferrous Sulphate",
    form: "Tablet",
    strength: "100 mg",
    dosage: "100 mg",
    dose: "100",
    doseUnit: "mg",
    frequency: "OD",
    days: "5",
    route: "Oral",
    instructions: "Give after lunch.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Refused",
    status: "Refused",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-07-04",
    scheduledTime: "14:00",
    nextDueTime: "Review",
    orderedQty: 5,
    dispensedQty: 5,
    receivedQty: 5,
    administeredQty: 0,
    remainingQty: 5,
    refusalReason: "Patient refused medication",
    cells: [{ date: "2026-06-30", time: "14:00", label: "100 mg refused", status: "refused" }],
  },

  {
    id: "nd-010",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    selectedPatientName: "Rahul Sharma",
    category: "Intermittent",
    name: "Ceftriaxone",
    drugName: "Ceftriaxone",
    genericName: "Ceftriaxone",
    form: "Injection",
    strength: "1 g",
    dosage: "1 g",
    dose: "1",
    doseUnit: "g",
    frequency: "BD",
    days: "5",
    route: "IV",
    instructions: "Flush line before and after dose.",
    priority: "Routine",
    orderStatus: "Received",
    administrationStatus: "Partial",
    status: "Partial",
    orderDate: "2026-06-30",
    startDate: "2026-06-30",
    endDate: "2026-07-04",
    scheduledTime: "08:00",
    nextDueTime: "Continue",
    orderedQty: 10,
    dispensedQty: 6,
    receivedQty: 4,
    administeredQty: 0.5,
    remainingQty: 0.5,
    partialReason: "Only half dose administered due to patient discomfort",
    lastAdministeredAt: "08:15",
    lastAdministeredBy: "Maya Iyer",
    cells: [{ date: "2026-06-30", time: "08:00", label: "0.5 g partial", status: "partial" }],
  },

  {
    id: "nd-011",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    category: "Scheduled",
    name: "Cefixime",
    drugName: "Cefixime",
    genericName: "Cefixime",
    form: "Tablet",
    strength: "200 mg",
    dosage: "200 mg",
    dose: "200",
    doseUnit: "mg",
    frequency: "BD",
    days: "3",
    route: "Oral",
    instructions: "Returned due wrong strength.",
    priority: "Routine",
    orderStatus: "Returned",
    administrationStatus: "Returned",
    status: "Returned",
    orderDate: "2026-06-30",
    orderedQty: 6,
    dispensedQty: 6,
    receivedQty: 6,
    administeredQty: 0,
    remainingQty: 6,
    reconciliationStatus: "Mismatch",
    reconciliationRemarks: "Wrong strength returned to pharmacy.",
    cells: [{ date: "2026-06-30", time: "16:00", label: "Returned", status: "empty" }],
  },

  {
    id: "nd-012",
    patientId: "UHID-1001",
    patientName: "Rahul Sharma",
    category: "Discontinued",
    name: "Ibuprofen",
    drugName: "Ibuprofen",
    genericName: "Ibuprofen",
    form: "Tablet",
    strength: "400 mg",
    dosage: "400 mg",
    dose: "400",
    doseUnit: "mg",
    frequency: "BD",
    days: "0",
    route: "Oral",
    instructions: "Stopped due gastritis.",
    priority: "Routine",
    orderStatus: "Discontinued",
    administrationStatus: "Discontinued",
    status: "Discontinued",
    orderDate: "2026-06-30",
    orderedQty: 10,
    dispensedQty: 10,
    receivedQty: 10,
    administeredQty: 2,
    remainingQty: 8,
    discontinuedReason: "Gastritis",
    lastAdministeredAt: "Yesterday 20:00",
    lastAdministeredBy: "Maya Iyer",
    cells: [{ date: "2026-06-30", time: "18:00", label: "Stopped", status: "empty" }],
  },
];

export const defaultAdministrationDetail: AdministrationDetail = {
  orderId: "nd-002",
  orderName: "Pantoprazole",
  category: "Scheduled",
  administrationDate: "2026-06-30",
  dosage: "40 mg",
  time: "07:00",
  priority: "Routine",
  lastAdministeredAt: "06:05",
  lastAdministeredBy: "Maya Iyer",
  action: "Late administered",
  reason: "Scheduled dose overdue",
  administrationNote: "Late administration demo case.",
  counterChecked: false,
  counterCheckedBy: "",
  counterCheckedAt: "",
};

export const defaultFluidDetail: FluidAdministrationDetail = {
  orderId: "nd-006",
  orderName: "Normal Saline",
  category: "Continuous",
  administrationDate: "2026-06-30",
  rate: "20 ml/hr",
  time: "10:00",
  diluent: "Normal Saline",
  lastAdministeredAt: "10:00",
  lastAdministeredBy: "Nisha Thomas",
  counterCheckedBy: "",
  counterCheckedAt: "",
  counterChecked: false,
  bagVolume: "500",
  volumeAdministered: "180",
  volumeRemaining: "320",
  newBag: false,
  bagCount: "1",
  bolusDose: "20 ml",
  bolusRoute: "IV push",
  stopAdministrationAt: "",
  reason: "",
};