export type DrugCategory = "Scheduled" | "SOS" | "STAT" | "Bolus" | "Diluent" | "Intermittent" | "Continuous" | "Discontinued" | "Unscheduled";
export type DraftCategory = DrugCategory | "";
export type DoseUnit =| ""| "mg"| "microgram"| "g"| "ml"| "litre"| "units"| "units/hr"| "drops"| "puffs"| "mcg/kg/min"| "mg/kg/min";
export type DurationUnit = "Days" | "Weeks" | "Months";
export type TimeUnit = "" | "sec" | "min" | "hour" | "day";
export type DrugScope = "Available Drugs" | "All Drugs";

export type DrugOrder = {
  id: string;
  name: string;
  form: string;
  genericName: string;
  dosage: string;
  doseUnit: DoseUnit;
  maxDosage: string;
  frequency: string;
  days: string;
  route: string;
  availableQty: number;
  pharmacy: string;
  hasContraindication?: boolean;
  diluents?: string[];
  startDate: string;
  endDate: string;
  instructions: string;
  category: DrugCategory;
  orderedQty: number;
  dispensedQty: number;
  receivedQty: number;
  administeredQty: number;
  discontinuedReason?: string;
  isHistorical?: boolean;
  modifiedFromId?: string;
};

export type TaperDose = {
  id: string;
  dose: string;
  unit: DoseUnit;
  frequency: string;
  fromDate: string;
  toDate: string;
};

export type OrderDraft = {
  name: string;
  genericName: string;
  form: string;
  dosage: string;
  maxDosage: string;
  frequency: string;
  days: string;
  dayUnit: DurationUnit;
  startDate: string;
  startTime: string;
  endDate: string;
  endTime: string;
  instructions: string;
  category: DraftCategory;
  orderedQty: string;
  route: string;
  doseUnit: DoseUnit;
  maxDoseUnit: DoseUnit;
  pharmacy: string;
  drugScope: DrugScope;
  site: string;
  diluent: string;
  sos: boolean;
  stat: boolean;
  bolus: boolean;
  intermittent: boolean;
  continuous: boolean;
  bolusDose: string;
  bolusUnit: DoseUnit;
  bolusKg: boolean;
  rateDose: string;
  rateUnit: DoseUnit;
  rateTimeUnit: TimeUnit;
  rateKg: boolean;
  totalDose: string;
  totalDoseUnit: DoseUnit;
  totalDuration: string;
  totalDurationUnit: TimeUnit;
  dosageCalcDose: string;
  dosageCalcUnit: DoseUnit;
  dosageCalcTimeUnit: TimeUnit;
  dosageCalcFrequency: string;
  dosageCalcKg: boolean;
  dosageCalcFreq: boolean;
  weightKg: string;
  hasContraindication: boolean;
  taperEntry: TaperDose;
  taperDoses: TaperDose[];
};
